### ISSUE TITLE
文章進度亂跳

### ISSUE THREAD

**Issue by Hsiao-Yu** [WeilJimmer/WBReader#2]
看到一半不小心按到畫面中間，目錄跳出來的時候文章進度會跑掉，明明滑到中間結果按到目錄文章就跳到開頭了，更新前沒有這個問題

**Comment by WeilJimmer** [comment]
您好，未測試出問題。

請描述清楚您的閱讀模式，是 TXT 還是 EPUB ，有沒有開啟上下捲動，如果是 TXT 有沒有開啟「使用原生組件繪圖」。

按到中間是跳出選單而不是目錄，必須有兩步操作才會打開目錄。

打開選單，再點目錄後，顯示出目錄的當下才跳到文章開頭？

詳細的描述所有過程包含您使用的安卓設備，安卓版本，應用程式版本以及再現步驟，對於解決本問題較有幫助。

**Comment by Hsiao-Yu** [comment]
您好，
使用的是TXT文檔，有開啟上下捲動，顯示快速捲動條
按到中間跳出的是選單(因為回報時忘記這個名詞所以稱為目錄)，

安卓設備：三星Note20 ultra
安卓版本：12
One UI版本：4.0
應用程式版本：1.2.3.02
再現步驟：
    開啟文檔後，使用快速捲動條拉到某定位開始看，按到中間開啟選單後，進度會回歸文檔開啟當下的進度。
    (這兩天嘗試後發現使用快速捲動條較容易觸發此問題，但滑動頁面觀看偶爾也會發生此問題)

**Comment by WeilJimmer** [comment]
已於版本 12304 修復。
